bbs/urls.py
from django.urls import path
# from ratelimit.decorators import ratelimit

from bbs.comments import comments
from bbs.users import users_view
from bbs.blogs import my_blogs
from bbs.blogs import category
from bbs.blogs import topics

urlpatterns = [
    # 个人中心
    path('user_center/', users_view.UserCenter.as_view(), name='user_center'),
    path('users/settings/edit/', users_view.UserProfile.as_view(), name='edit_profile'),
    path('users/settings/update/', users_view.UserProfile.post, name='upload_profile'),
    path('users/settings/edit_avatar/', users_view.UserAvatar.as_view(), name='edit_avatar'),
    path('users/settings/edit_phone/', users_view.UserBindPhone.as_view(), name='edit_phone'),
    path('users/settings/edit_password/', users_view.UserChangePassword.as_view(), name='edit_password'),
    path('categories/<int:category_id>/', category.CategoryView.as_view(), name='category_show'),
    path('topics/<int:topic_id>/', topics.TopicView.as_view(), name='topic_show'),
    path('topics/edit/<int:topic_id>/', topics.UpdateTopicView.as_view(), name="edit_topic"),
    path('topics/update/', topics.UpdateTopicView.as_view(), name="update_topic"),
    path('topics/delete/', topics.DeleteTopicView.as_view(), name="delete_topic"),

    # 我的博客
    path('blog/<str:username>/', my_blogs.MyBlog.as_view(), name='blog_center'),
    path('blog/<str:username>/archive/<slug:slug>', my_blogs.MyBlog.as_view(), name='blog_center'),
    # 新建博文
    path('topic/create/', my_blogs.CreateTopic.as_view(), name='create_topic'),
    # 点赞踩
    path('like/', my_blogs.like, name='like'),
    path('hate/', my_blogs.hate, name='hate'),
    # 评论
    path('comment/', comments.Comment.as_view(), name='commit'),
]

djangoBBS/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from bbs import views
from djangoBBS import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # 首页
                  path('', views.index, name='home'),
                  # 注册
                  path('reg/', views.reg, name='register'),
                  # 登录
                  path('login/', views.login, name='login'),
                  # 退出
                  path('logout/', views.logout, name='logout'),
                  path('forget/', views.forget, name='forget_change_pwd'),
                  path('bbs/', include('bbs.urls')),
                  # media配置
                  # re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})

                  # 富文本
                  re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbs/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
import os
import uuid

from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import AbstractUser
from django.db import models
from ckeditor.fields import RichTextField

from .storage import ImageStorage


class Categories(models.Model):
    name = models.CharField(max_length=50, verbose_name='分类名称')
    description = models.TextField(blank=True, null=True, verbose_name='分类描述')
    post_count = models.PositiveIntegerField(verbose_name='帖子个数', default=0)
    create_time = models.IntegerField(verbose_name='创建时间')
    update_time = models.IntegerField(blank=True, null=True, verbose_name='更新时间')

    class Meta:
        db_table = 'categories'
        verbose_name = '帖子分类表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Comments(models.Model):
    id = models.AutoField(primary_key=True)
    pid = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    content = models.TextField()
    topic = models.ForeignKey(to="Topics", to_field="id", on_delete=models.CASCADE)
    user = models.ForeignKey(to="Users", to_field="id", on_delete=models.CASCADE)
    level = models.CharField(max_length=255, verbose_name='评论层级', default='')

    class Meta:
        db_table = 'comments'
        verbose_name = '评论表'
        verbose_name_plural = verbose_name

    def children(self):
        return self.objects.filter(pid=self)


class Notifications(models.Model):
    title = models.CharField(max_length=191)
    content = models.TextField(blank=True, null=True)
    user = models.ForeignKey(to="Users", to_field="id", on_delete=models.CASCADE)
    is_read = models.PositiveIntegerField(default=0)
    create_time = models.IntegerField()
    update_time = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = 'notifications'
        verbose_name = '通知表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Tags(models.Model):
    title = models.CharField(max_length=50)
    user = models.ForeignKey(to="Users", to_field="id", on_delete=models.CASCADE)
    topic = models.ForeignKey(to="Topics", to_field="id", on_delete=models.CASCADE)

    class Meta:
        db_table = 'tags'
        verbose_name = '标签表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Topics(models.Model):
    title = models.CharField(max_length=64)
    body = RichTextUploadingField(blank=True, null=True)
    user = models.ForeignKey(to="Users", to_field="id", on_delete=models.CASCADE)
    category = models.ForeignKey(to="Categories", to_field="id", on_delete=models.CASCADE)
    reply_count = models.PositiveIntegerField(default=0)
    view_count = models.PositiveIntegerField(default=0)
    sort = models.PositiveIntegerField(default=0)
    create_time = models.PositiveIntegerField()
    update_time = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        db_table = 'topics'
        verbose_name = '帖子表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Collects(models.Model):
    user = models.ForeignKey(to="Users", to_field="id", on_delete=models.CASCADE)
    topic = models.ForeignKey(to="Topics", to_field="id", on_delete=models.CASCADE)
    topic_name = models.CharField(max_length=50, verbose_name='收藏的帖子标题')

    class Meta:
        db_table = "collects"
        verbose_name = '收藏表'
        verbose_name_plural = verbose_name
        unique_together = (('user', 'topic'),)


class Likes(models.Model):
    user = models.ForeignKey(to="Users", to_field="id", on_delete=models.CASCADE)
    topic = models.ForeignKey(to="Topics", to_field="id", on_delete=models.CASCADE)
    is_like = models.PositiveIntegerField(default=0)

    class Meta:
        db_table = 'likes'
        verbose_name = '点赞表'
        verbose_name_plural = verbose_name


class Users(AbstractUser):
    id = models.AutoField(primary_key=True)
    nickname = models.CharField(max_length=50, blank=True, null=True)
    avatar = models.FileField(upload_to="avatar/%Y%m", default="/avatars/avatar.jpg", storage=ImageStorage())
    last_login_ip = models.CharField(max_length=64)
    update_time = models.IntegerField(blank=True, null=True)
    sex = models.PositiveIntegerField(default=0)
    email = models.CharField(max_length=64)
    mobile = models.CharField(max_length=11, blank=True, null=True)
    birthday = models.DateTimeField(blank=True, null=True)
    introduction = models.TextField(blank=True, null=True)
    github = models.CharField(max_length=255, blank=True, null=True)
    qq = models.CharField(max_length=12, blank=True, null=True)
    sign = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'users'
        verbose_name = '用户表'


class Log(models.Model):
    user = models.ForeignKey(to="Users", to_field="id", on_delete=models.CASCADE)
    level = models.CharField(max_length=32, verbose_name='异常级别', default='info')
    request_path = models.CharField(max_length=191, verbose_name='请求地址')
    ip = models.CharField(max_length=64)
    params = models.TextField(verbose_name='请求参数')
    content = models.TextField(verbose_name='异常内容', null=True, blank=True)
    create_time = models.PositiveIntegerField()

    class Meta:
        db_table = 'logs'
        verbose_name = '日志记录表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.level

templates/my_blogs/archive.html
<div class="card">
    <div class="card-header">
        <h4 class="card-title">文章归档</h4>
    </div>
    <div class="card-body">
        <ul class="list-group">
            {% if date_list %}
                {% for date in date_list %}
                    <li class="list-group-item">
                        <a href="{% url 'blog_center' bloger.username date.y_m_date %}">
                            {{ date.y_m_date }}
                            <span class="badge badge-secondary">{{ date.c }}</span>
                        </a>
                    </li>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
</div>

templates/my_blogs/blog_center.html
{% extends 'layout/app.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/users/user_center.css">
{% endblock %}

{% block title %}
    {{ request.user.username }}的博客
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-4 col-md-4 col-lg-4">
            <div class="row">
                <div class="col-sm-12">
                    {% include 'my_blogs/left_bloger.html' %}
                </div>
            </div>
            {% if bloger.id == request.user.id %}
                <div class="row mt-2">
                    <div class="col-sm-12">
                        <a href="{% url 'create_topic' %}" class="btn btn-success w-100">
                            <i class="fa fa-paint-brush"></i>
                            撰写文章
                        </a>
                    </div>
                </div>
            {% endif %}
            <div class="row mt-2">
                <div class="col-sm-12">
                    {% include 'my_blogs/archive.html' %}
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-sm-12">
                    {% include 'my_blogs/user_tags.html' %}
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            {% include 'my_blogs/user_all_topics.html' %}
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>

    </script>
{% endblock %}

templates/my_blogs/create.html
{% extends 'layout/app.html' %}

{% block title %}
    新建文章
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/css/jquery.tagsinput.min.css">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <form id="create_topic">
                {% csrf_token %}
                <div class="form-group row">
                    {{ create_topic_form.category }}
                    {{ create_topic_form.title }}
                </div>
                <div class="form-group row">
                    {#                    {{ create_topic_form.body }}#}
                    <textarea name="body" id="body" cols="30" rows="10"></textarea>
                </div>

                <div class="form-group row">
                    <input type="text" class="form-control" id="tags" name="tags"
                           placeholder="输入标签Enter确认"/>
                </div>

                <div class="form-group row">
                    <button type="button" class="btn_publish btn btn-success">发布文章</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    {% load static %}
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script src="/static/js/jquery.tagsinput.min.js"></script>

    <script>

        window.onload = function () {
            CKEDITOR.replace('body');
            $("#tags").tagsInput();
        }

        $(".django-ckeditor-widget").removeAttr('style');

        $(document).on("click", ".btn_publish", function () {
            var text_area_data = CKEDITOR.instances.body.getData();
            {#console.log(text_area_data)#}
            var tags = $("#tags").val();
            {#var tags_arr = tags.split(",")#}
            {#console.log(tags, tags_arr);#}
            {#return false;#}
            request("", {
                data: {
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                    "category": $("#id_category").find("option:selected").val(),
                    "title": $("#id_title").val(),
                    "body": text_area_data,
                    "tags": tags
                },
                dataType: "json",
                type: "POST"
            }, "{% url 'home' %}");
        });
    </script>
{% endblock %}

templates/my_blogs/left_bloger.html
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-3 offset-lg-1">
                {{ bloger.username }}
                {% if bloger.id == request.user.id %}
                    <a href="{% url 'edit_profile' %}"><i class="fa fa-edit"></i></a>
                {% endif %}
            </div>
            <div class="col-sm-2 offset-sm-5">
                <img src="/media/{{ bloger.avatar }}" alt="头像"
                     style="width: 44px;height: 44px;">
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="ml-3">文章: {{ topics.count }}</div>
            <div class="ml-3">点赞: {{ likes }}</div>
            <div class="ml-3">收藏: {{ collects }}</div>
        </div>
    </div>
</div>

templates/my_blogs/user_all_topics.html
<div class="card">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fa fa-book"></i>
            {% if slug %}
                {{ slug }}的文章
            {% else %}
                所有文章
            {% endif %}
        </h3>
    </div>
    <div class="card-body">
        <div class="blog">
            {% for topic in topics %}
                <div class="event">
                    <div class="content">
                        <div class="summary">
                            <a href="{% url 'topic_show' topic.id %}">{{ topic.title }}</a>
                        </div>
                        <div class="meta" style="line-height: 34px;">
                            <div class="date"
                                 style="font-size: 13px;margin: 7px 0 0 0;">
                                {% load mylabel %}
                                <a class="" data-tooltip="{{ topic.create_time|timestamp }}">创建于 <span
                                        title="{{ topic.create_time|timestamp }}">{{ topic.create_time|timestamp }}</span></a>
                                <span class="divider">|</span>
                                <a>
                                    阅读数 {{ topic.view_count }}
                                </a>
                                <span class="divider">|</span>
                                <a>
                                    评论数 {{ topic.reply_count }}
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="item-meta">
                        {% if topic.user.id == request.user.id %}
                            <a class="btn btn-sm"
                               href="javascript:;" onclick="layer.msg('不能对自己的文章点赞哦');" data-topic_id="{{ topic.id }}"><i
                                    class="fa fa-thumbs-o-up"></i> {{ topic.like_num }}
                            </a>
                            <a class="btn btn-sm"
                               href="javascript:;" onclick="layer.msg('你还想踩自己的文章?');" data-topic_id="{{ topic.id }}"><i
                                    class="fa fa-thumbs-o-down"></i> {{ topic.hate_num }}
                            </a>
                        {% else %}
                            <a class="btn btn-sm btn_like"
                               href="javascript:;" data-topic_id="{{ topic.id }}"><i
                                    class="fa fa-thumbs-o-up"></i> {{ topic.like_num }}
                            </a>
                            <a class="btn btn-sm btn_hate"
                               href="javascript:;" data-topic_id="{{ topic.id }}"><i
                                    class="fa fa-thumbs-o-down"></i> {{ topic.hate_num }}
                            </a>
                        {% endif %}

                        <a class="ui label basic light grey"
                           href=""><i class="fa fa-comment"></i> {{ topic.comment_num }}
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/my_blogs/user_tags.html
<div class="card">
    <div class="card-header">
        <h5 class="card-title">博客标签</h5>
    </div>
    <div class="card-body">
        <div class="row">
            {% for tag in tags %}
                <div class="col-sm-4">
                    <a href="">
                        <span class="w-50 badge badge-pill">{{ tag.title }} {{ tag.c }}</span>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>